services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db
  
  db:
    image: postgis/postgis:14-3.3
    restart: unless-stopped
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dagger
      - POSTGRES_DB=dagger
      - POSTGRES_PASSWORD=dagger
