"""create users table

Revision ID: e2aa5f22a763
Revises: 
Create Date: 2023-06-29 03:24:55.642675

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2aa5f22a763"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_email"), "users", ["email"], unique=True, schema="public"
    )
    op.create_index(
        op.f("ix_public_users_id"), "users", ["id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_users_id"), table_name="users", schema="public")
    op.drop_index(op.f("ix_public_users_email"), table_name="users", schema="public")
    op.drop_table("users", schema="public")
    # ### end Alembic commands ###
