name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install libsqlite3-mod-spatialite
      - run: pipx install poetry
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install -n
      - name: Linting
        run: poetry run pre-commit run
      - name: Tests
        run: poetry run pytest
